name: Release AutoHotkey Script
on: [push, repository_dispatch]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Compile AutoHotkey
      uses: benmusson/ahk2exe-action@v1
      with:
        in: src/Arknights.ahk
        out: Arknights.ahk.exe
        compression: none

    - name: Set current date as env variable
      shell: bash
      run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: src/Arknights.ahk.exe
        tag: ${{ env.TODAY }}
        commit: master
        allowUpdates: true
        generateReleaseNotes: true
